apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ko45naasu-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ko45naasu-java-quarkus-gitops